[Eth]
NetworkId = 9999
SyncMode = "full"
DiscoveryURLs = []
NoPruning = false
NoPrefetch = false
LightPeers = 100
UltraLightFraction = 75
DatabaseCache = 512
DatabaseFreezer = ""
TrieCleanCache = 256
TrieDirtyCache = 256
TrieTimeout = 3600000000000
EnablePreimageRecording = false
EWASMInterpreter = ""
EVMInterpreter = ""

[Eth.Miner]
GasFloor = 8000000
GasCeil = 8000000
GasPrice = 1000000000
Recommit = 3000000000
Noverify = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
CachesLockMmap = false
DatasetDir = "/home/simon/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
DatasetsLockMmap = false
PowMode = 0

[Eth.TxPool]
Locals = []
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01
RestrictConnectionBetweenLightClients = true

[Node]
UserIdent = "DuckChain_PublicNode01"
DataDir = "/home/simon/DuckChain/data/DuckChain_PublicNode01"
omitempty = ""
IPCPath = "geth.ipc"
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]
GraphQLPort = 8547
GraphQLVirtualHosts = ["localhost"]

[Node.P2P]
MaxPeers = 50
NoDiscovery = false
BootstrapNodes = ["enode://4cb93c54e4678f853fab060154f8646622b301488d8083d20e839655c8d3f820f8e2e7f866df67e6d5ef1f71167a2c1a7cc73ba1d9b39c63822ed7a693fa666f@82.64.158.44:30303"]
BootstrapNodesV5 = []
StaticNodes = ["enode://4cb93c54e4678f853fab060154f8646622b301488d8083d20e839655c8d3f820f8e2e7f866df67e6d5ef1f71167a2c1a7cc73ba1d9b39c63822ed7a693fa666f@82.64.158.44:30303"]
TrustedNodes = ["enode://4cb93c54e4678f853fab060154f8646622b301488d8083d20e839655c8d3f820f8e2e7f866df67e6d5ef1f71167a2c1a7cc73ba1d9b39c63822ed7a693fa666f@82.64.158.44:30303"]
ListenAddr = ":30305"
EnableMsgEvents = false

[Node.HTTPTimeouts]
ReadTimeout = 30000000000
WriteTimeout = 30000000000
IdleTimeout = 120000000000

[Ethstats]
URL = "DuckChain_PublicNode01:12345@192.168.0.250:3000"
